# Generated by Django 5.0.4 on 2025-02-04 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfoodselection',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='cuisine',
            field=models.CharField(choices=[('Italian', 'Italian'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Mexican', 'Mexican'), ('Indian', 'Indian'), ('French', 'French'), ('American', 'American')], default='Unset', max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Protein', 'Protein'), ('Carbohydrate', 'Carbohydrate'), ('Fat', 'Fat'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Dairy', 'Dairy')], default='Unset', max_length=20),
        ),
        migrations.AddField(
            model_name='userfoodselection',
            name='disliked_foods',
            field=models.ManyToManyField(blank=True, related_name='disliked_by_users', to='webapp.food'),
        ),
        migrations.AddField(
            model_name='userfoodselection',
            name='liked_foods',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='webapp.food'),
        ),
        migrations.AlterField(
            model_name='userfoodselection',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
