# Generated by Django 5.0.4 on 2025-02-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cuisine_foodcategory_alter_food_cuisine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietaryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userfoodselection',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='user_allergy', to='webapp.allergy'),
        ),
        migrations.AddField(
            model_name='userfoodselection',
            name='dietary_requirement',
            field=models.ManyToManyField(blank=True, related_name='user_dietary_requirement', to='webapp.dietaryrequirement'),
        ),
    ]
