# Generated by Django 5.0.4 on 2025-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_allergy_dietaryrequirement_userfoodselection_allergy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userfoodselection',
            name='health_goals',
            field=models.ManyToManyField(blank=True, related_name='user_health_goal', to='webapp.healthgoals'),
        ),
    ]
