# Generated by Django 5.0.4 on 2025-02-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_healthgoals_userfoodselection_health_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthgoals',
            name='extraInfo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
