# Generated by Django 5.0.4 on 2025-02-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_healthgoals_extrainfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthgoals',
            name='extraInfo',
        ),
    ]
