# Generated by Django 5.2 on 2025-04-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_healthgoals_extrainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_type',
        ),
        migrations.AddField(
            model_name='food',
            name='food_types',
            field=models.ManyToManyField(blank=True, to='webapp.foodcategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='flavor_profile',
            field=models.ManyToManyField(blank=True, to='webapp.flavorprofile'),
        ),
        migrations.AddField(
            model_name='food',
            name='texture_profile',
            field=models.ManyToManyField(blank=True, to='webapp.textureprofile'),
        ),
    ]
